# Generated by Django 3.2.8 on 2022-06-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('cpf', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('id_product', models.IntegerField(max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('id_sale', models.IntegerField(max_length=30)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
