# Generated by Django 3.2.8 on 2022-06-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='id_product',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id_sale',
            field=models.IntegerField(),
        ),
    ]
