# Generated by Django 3.2.8 on 2022-06-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20220609_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='id_product',
            field=models.TextField(),
        ),
    ]
