# Generated by Django 3.2.8 on 2022-06-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_sale_id_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='id_sale',
        ),
        migrations.AlterField(
            model_name='sale',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id_product',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sale',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
    ]
