# Generated by Django 3.2.8 on 2022-06-12 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220612_1939'),
        ('sale', '0004_auto_20220610_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='id_product',
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='products.product'),
        ),
    ]
