# Generated by Django 3.2.8 on 2022-06-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20220612_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_value',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
