# Generated by Django 3.2.8 on 2022-06-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_auto_20220613_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product_id',
        ),
        migrations.AddField(
            model_name='sale',
            name='product_slug',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
