# Generated by Django 3.2.8 on 2022-06-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_auto_20220613_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product_slug',
        ),
        migrations.AddField(
            model_name='sale',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
    ]
