# Generated by Django 3.2.8 on 2022-06-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('estoque', models.IntegerField()),
                ('is_available', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
